### ISSUE TITLE
Create a convertor which will automatically transform webpackConfig into chainWebpack syntax

### ISSUE THREAD

**Issue by ttodua** [neutrinojs/webpack-chain#281] opened 2020-10-21 11:37 UTC
So many people needs this feature, would be excellent if it will be done. At this moment, we have to manually learn how to rewrite webpack.config.js into chainWebpack syntaxes (i.e. for Vue-Cli or alike)

**Comment by timkelty** [comment] 2020-10-21 14:17
Love this idea!

**Comment by edmorley** [comment] 2021-12-13 08:25
Duplicate of #272

**Closed by edmorley** 2021-12-13 08:25 UTC
